#!/bin/sh
#                            The MIT License
#
#        Copyright (c) 2014 Marcelo Guimaraes <ataxexe@gmail.com>
# ----------------------------------------------------------------------
# Permission  is hereby granted, free of charge, to any person obtaining
# a  copy  of  this  software  and  associated  documentation files (the
# "Software"),  to  deal  in the Software without restriction, including
# without  limitation  the  rights to use, copy, modify, merge, publish,
# distribute,  sublicense,  and/or  sell  copies of the Software, and to
# permit  persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The  above  copyright  notice  and  this  permission  notice  shall be
# included  in  all  copies  or  substantial  portions  of the Software.
#                        -----------------------
# THE  SOFTWARE  IS  PROVIDED  "AS  IS",  WITHOUT  WARRANTY OF ANY KIND,
# EXPRESS  OR  IMPLIED,  INCLUDING  BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN  NO  EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM,  DAMAGES  OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT  OR  OTHERWISE,  ARISING  FROM,  OUT OF OR IN CONNECTION WITH THE
# SOFTWARE   OR   THE   USE   OR   OTHER   DEALINGS  IN  THE  SOFTWARE.

_rboss_cli () {
  COMPREPLY=()
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local prev="${COMP_WORDS[COMP_CWORD-1]}"
  local args="${COMP_WORDS[@]:1}"
  local prev_args="${COMP_WORDS[@]:1:COMP_CWORD-1}"

  case "$cur" in
    - | --*)
      COMPREPLY=( $( compgen -W '$(rboss-cli options)' -- $cur ) )
    ;;
    *)
    case "$prev" in
      --connect)
        COMPREPLY=( $( compgen -W '$(rboss-cli --list-servers)' -- $cur ) )
      ;;
      -o | --operation | \
      -d | --detail)
        COMPREPLY=( $( compgen -W '$(rboss-cli $prev_args read-operation-names)' -- $cur ) )
      ;;
      -j | --jboss-home | --script)
        _longopt
      ;;
      --domain-host)
        COMPREPLY=( $( compgen -W '$(rboss-cli ${prev_args/--domain-host//} --hosts)' -- $cur ) )
      ;;
      --domain-server)
        COMPREPLY=( $( compgen -W '$(rboss-cli ${prev_args/--domain-server//} --servers)' -- $cur ) )
      ;;
      -v | -s | -u | -p | -l | -r | \
      --list-operations | \
      --list-resource-names | \
      --verbose | \
      --host | \
      --port | \
      --save | \
      --list-servers | \
      --start-cli | \
      --native | \
      --no-colors | \
      --attribute | \
      --all | \
      --scan)
      ;;
      --*)
        if [[ "$cur" =~ .*,.* ]]; then
          COMPREPLY=( $( compgen -W '$(rboss-cli $args --list-resource-names)' \
            -P "${cur%,*}," -- ${cur##*,} ) )
        else
          COMPREPLY=( $( compgen -W '$(rboss-cli $args --list-resource-names)' -- $cur ) )
        fi
      ;;
    esac
    ;;
  esac
  return 0
}

complete -F _rboss_cli -o nospace rboss-cli